name: "Git2Go"
description: "An Umbrella GitHub Action providing multiple functionalities."
author: "TENZIN TASHI <TENZIN.TASHI@AEXP.COM>"

inputs:
  action_name:
    description: "The name of the action to be invoked."
    required: true
  config:
    description: |
      Inline YAML config for the selected action
      
      Optional: top-level `platform:` block overrides platform defaults
      Example:
      
      platform:
        github_server_url: ${{ github.server.url }}
        artifactory_toke: ${{ secrets.ARTIFACTORY_TOKEN }}
      command: "mvn -q -DskipTests test"
      working_dir: "."
    required: true

runs:
  using: docker
  image: ${{ secrets.DOCKER_PAAS_REGISTRY }}/${{ github.repository }}/__MAJOR__:__TAG__
