name: "Git2Go"
description: "An Umbrella GitHub Action providing multiple functionalities."
inputs:
  action_name:
    description: "The name of the action to be invoked."
    required: true


runs:
  using: "composite"
  steps:
    - name: "Print specific GITHUB environment variables"
      run: |
        echo "GITHUB_ACTION_REPOSITORY: $GH_ACTION_REPOSITORY"
        echo "GITHUB_ACTION_REF: $GH_ACTION_REF"
      shell: bash
      env:
        GH_ACTION_REPOSITORY: ${{ github.action_repository}}
        GH_ACTION_REF: ${{ github.action_ref }}
    #  using: 'docker'
    #  image: 'Dockerfile'
    #  args: |
    #    --build-arg JAR_FILE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
    #    "https://github.aexp.com/api/v3/repos/${{ github.repository }}/releases/tags/${GITHUB_REF##*/}" | \
    #    jq -r '.assets[0].name')
    
