name: "Git2Go"
description: "An Umbrella GitHub Action providing multiple functionalities."
inputs:
  action_name:
    description: "The name of the action to be invoked."
    required: true


runs:
  using: "composite"
  env:
    GH_TOKEN: ${{ github.token }}
    GH_ACTION_REPOSITORY: ${{ github.action_repository}}
    GH_ACTION_REF: ${{ github.action_ref }}
  steps:
    - name: Fetch the release asset dynamically
      id: fetch-release-asset
      run: |
        # Fetch the release asset dynamically
        RELEASE_JSON=$(curl -s -H "Authorization: token $GH_TOKEN" \
            "https://github.aexp.com/api/v3/repos/$GH_ACTION_REPOSITORY/releases/tags/$GH_ACTION_REF")
        RELEASE_ASSET_URL=$(echo $RELEASE_JSON | jq -r '.assets[0].browser_download_url')
        
        # Download the JAR file
        curl -L -H "Authorization: token $GH_TOKEN" -o /tmp/git2go.jar "$RELEASE_ASSET_URL"
        echo "JAR file downloaded: /tmp/git2go.jar"
      shell: bash

    - name: Run the action
      id: run-action
      run: |
        java -jar /tmp/git2go.jar ${{ inputs.action_name }}
      shell: bash
