#!/bin/bash

branch_name=$(git symbolic-ref --short HEAD)
lowercase_branch_name=$(echo "$branch_name" | tr '[:upper:]' '[:lower:]')
if [[ "$branch_name" != "$lowercase_branch_name" ]]; then
    echo "Branch name must be lowercase. Aborting commit."
    exit 1
fi
