#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

if ! mvn compile -T 4C -DskipTests -am; then
  echo -e "${RED}[Error]${NC} Maven build failed. Push aborted."
  exit 1
fi
echo -e "${GREEN}[INFO]${NC} Maven build succeeded. Proceeding with push."
exit 0
