#!/bin/bash

RED='\033[0;31m'
NC='\033[0m'

branch_name=$(git symbolic-ref --short HEAD)
lowercase_branch_name=$(echo "$branch_name" | tr '[:upper:]' '[:lower:]')

# Check if branch name is all lowercase
if [[ "$branch_name" != "$lowercase_branch_name" ]]; then
    echo -e "${RED}Error:${NC} Branch name must be lowercase. Aborting commit."
    exit 1
fi
